#pragma once

#define TABLE_MODE_EDIT				1
#define TABLE_MODE_CONST			2
#define TABLE_MODE_RAM				3
#define TABLE_MODE_HDD				4


#define TABLE_ROW_MODE_RAM			5
#define TABLE_ROW_MODE_HDD			6

#define TABLE_REGISTER_SCHEMA		99

#define TABLE_MODE_ADD				100
#define TABLE_MODE_CHECK_DUP_ADD	102
//#define TABLE_MODE_NO_CHECK_DUP_ADD	103

#define TABLE_MODE_VIEW_ALL			200
#define TABLE_MODE_VIEW_ONE			201

#define TABLE_MODE_MODIFY_ALL		300
#define TABLE_MODE_MODIFY_ONE		301

#define TABLE_MODE_DELETE_ONE		402

#define TABLE_PROP_NULL				500
#define TABLE_PROP_NOT_NULL			600
#define TABLE_UNIQUE				700

