name: C/C++ CI

on: [push]
jobs:
  Windows:
    runs-on: windows-2019
    env:
      VS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\'
      MSBUILD_PATH: >-
        C:\Program Files (x86)\Microsoft Visual
        Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-dept: 1
      - name: Build Project
        shell: cmd
        run: |
          cd build
          "%MSBUILD_PATH%\MSBuild.exe" MyDB.sln /p:Configuration=Release /m